src/main/default/objects/BP_Game__c/BP_Game__c.object-meta.xml
<CustomObject>
    <description>Game object</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_Game__c/fields/BP_bggId__c.field-meta.xml
<CustomField>
    <fullName>BP_bggId__c</fullName>
    <externalId>true</externalId>
    <label>BGG Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_HasExpansion__c.field-meta.xml
<CustomField>
    <fullName>BP_HasExpansion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Expansion</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_IsExpansion__c.field-meta.xml
<CustomField>
    <fullName>BP_IsExpansion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if game is expansion to another game</description>
    <label>Is Expansion</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_MaximumPlayersNumber__c.field-meta.xml
<CustomField>
    <fullName>BP_MaximumPlayersNumber__c</fullName>
    <label>Maximum Players Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_MinimumPlayersNumber__c.field-meta.xml
<CustomField>
    <fullName>BP_MinimumPlayersNumber__c</fullName>
    <label>Minimum Players Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_Publisher__c.field-meta.xml
<CustomField>
    <fullName>BP_Publisher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Publisher</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Games</relationshipLabel>
    <relationshipName>Games</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/selector/test/BP_GameSelectorTest.cls
/**
 * Created by Jedrzej Gruca on 08/02/2024.
 */

@IsTest
public with sharing class BP_GameSelectorTest {

    @TestSetup
    static void testSetup() {
        final Account publisher = new Account(
                Name = 'Publisher'
        );
        insert publisher;

        final BP_Game__c game = new BP_Game__c(
                Name = 'Gra',
                BP_MaximumPlayersNumber__c = 4,
                BP_MinimumPlayersNumber__c = 1,
                BP_bggId__c = 1000,
                BP_HasExpansion__c = true,
                BP_IsExpansion__c = true,
                BP_Publisher__c = publisher.Id
        );
        insert game;
    }

    @IsTest
    private static void selectByIdTest() {
        Id gameId = [SELECT Id FROM BP_Game__c WHERE Name = 'Gra'].get(0).Id;

        Test.startTest();
        final List<BP_Game__c> games = BP_GameSelector.newInstance().selectById(new Set<Id>{gameId});
        Test.stopTest();

        Assert.areEqual(1, games.size());
    }

    @IsTest
    private static void selectByIdAndHasExpansionTest() {
        Id gameId = [SELECT Id FROM BP_Game__c WHERE Name = 'Gra'].get(0).Id;

        Test.startTest();
        final List<BP_Game__c> games = BP_GameSelector.newInstance().selectByIdAndHasExpansion(new Set<Id>{gameId}, true);
        Test.stopTest();

        Assert.areEqual(1, games.size());
    }

    @IsTest
    private static void selectByPublisherIdTest() {
        Id publisherId = [SELECT Id FROM Account WHERE Name = 'Publisher'].get(0).Id;

        Test.startTest();
        final List<BP_Game__c> games = BP_GameSelector.newInstance().selectByPublisherId(new Set<Id>{publisherId});
        Test.stopTest();

        Assert.areEqual(1, games.size());
    }
}