src/main/default/objects/BP_Game__c/BP_Game__c.object-meta.xml
<CustomObject>
    <description>Game object</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_Game__c/fields/BP_Category__c.field-meta.xml
<CustomField>
    <fullName>BP_Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abstract Strategy</fullName>
            </value>
            <value>
                <fullName>Action / Dexterity</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Age of Reason</fullName>
            </value>
            <value>
                <fullName>American Civil War</fullName>
            </value>
            <value>
                <fullName>American Indian Wars</fullName>
            </value>
            <value>
                <fullName>American Revolutionary War</fullName>
            </value>
            <value>
                <fullName>American West</fullName>
            </value>
            <value>
                <fullName>Ancient</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Arabian</fullName>
            </value>
            <value>
                <fullName>Aviation / Flight</fullName>
            </value>
            <value>
                <fullName>Bluffing</fullName>
            </value>
            <value>
                <fullName>Book</fullName>
            </value>
            <value>
                <fullName>Card Game</fullName>
            </value>
            <value>
                <fullName>Children&apos;s Game</fullName>
            </value>
            <value>
                <fullName>City Building</fullName>
            </value>
            <value>
                <fullName>Civil War</fullName>
            </value>
            <value>
                <fullName>Civilization</fullName>
            </value>
            <value>
                <fullName>Collectible Components</fullName>
            </value>
            <value>
                <fullName>Comic Book / Strip</fullName>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
            <value>
                <fullName>Dice</fullName>
            </value>
            <value>
                <fullName>Economic</fullName>
            </value>
            <value>
                <fullName>Educational</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Expansion for Base-game</fullName>
            </value>
            <value>
                <fullName>Exploration</fullName>
            </value>
            <value>
                <fullName>Fan Expansion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_HasExpansion__c.field-meta.xml
<CustomField>
    <fullName>BP_HasExpansion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Expansion</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_IsExpansion__c.field-meta.xml
<CustomField>
    <fullName>BP_IsExpansion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if game is expansion to another game</description>
    <label>Is Expansion</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_Mechanic__c.field-meta.xml
<CustomField>
    <fullName>BP_Mechanic__c</fullName>
    <label>Mechanic</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acting</fullName>
            </value>
            <value>
                <fullName>Action Drafting</fullName>
            </value>
            <value>
                <fullName>Action Points</fullName>
            </value>
            <value>
                <fullName>Action Queue</fullName>
            </value>
            <value>
                <fullName>Action Retrieval</fullName>
            </value>
            <value>
                <fullName>Action Timer</fullName>
            </value>
            <value>
                <fullName>Action/Event</fullName>
            </value>
            <value>
                <fullName>Advantage Token</fullName>
            </value>
            <value>
                <fullName>Alliances</fullName>
            </value>
            <value>
                <fullName>Area Majority / Influence</fullName>
            </value>
            <value>
                <fullName>Area Movement</fullName>
            </value>
            <value>
                <fullName>Area-Impulse</fullName>
            </value>
            <value>
                <fullName>Auction Compensation</fullName>
            </value>
            <value>
                <fullName>Auction: Dexterity</fullName>
            </value>
            <value>
                <fullName>Auction: Dutch</fullName>
            </value>
            <value>
                <fullName>Auction: Dutch Priority</fullName>
            </value>
            <value>
                <fullName>Auction: English</fullName>
            </value>
            <value>
                <fullName>Auction: Fixed Placement</fullName>
            </value>
            <value>
                <fullName>Auction: Multiple Lot</fullName>
            </value>
            <value>
                <fullName>Auction: Once Around</fullName>
            </value>
            <value>
                <fullName>Auction: Sealed Bid</fullName>
            </value>
            <value>
                <fullName>Auction: Turn Order Until Pass</fullName>
            </value>
            <value>
                <fullName>Auction/Bidding</fullName>
            </value>
            <value>
                <fullName>Automatic Resource Growth</fullName>
            </value>
            <value>
                <fullName>Betting and Bluffing</fullName>
            </value>
            <value>
                <fullName>Bias</fullName>
            </value>
            <value>
                <fullName>Bids As Wagers</fullName>
            </value>
            <value>
                <fullName>Bingo</fullName>
            </value>
            <value>
                <fullName>Bribery</fullName>
            </value>
            <value>
                <fullName>Campaign / Battle Card Driven</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_RecommendedAge__c.field-meta.xml
<CustomField>
    <fullName>BP_RecommendedAge__c</fullName>
    <label>Recommended Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_Type__c.field-meta.xml
<CustomField>
    <fullName>BP_Type__c</fullName>
    <description>Type of the game</description>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customisable Games</fullName>
            </value>
            <value>
                <fullName>Children&apos;s Games</fullName>
            </value>
            <value>
                <fullName>Family Games</fullName>
            </value>
            <value>
                <fullName>Party Games</fullName>
            </value>
            <value>
                <fullName>Strategy Games</fullName>
            </value>
            <value>
                <fullName>Thematic Games</fullName>
            </value>
            <value>
                <fullName>Wargames</fullName>
            </value>
            <value>
                <fullName>Abstract Games</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/classes/selector/BP_GameSelector.cls
/**
 * Created by Jedrzej Gruca on 04/11/2023.
 */

public with sharing class BP_GameSelector extends fflib_SObjectSelector implements BP_IGameSelector {

    public BP_GameSelector() {
        super();
    }

    public static BP_GameSelector newInstance() {
        return (BP_GameSelector) BP_Application.selector.newInstance(BP_Game__c.SObjectType);
    }

    public SObjectType getSObjectType() {
        return BP_Game__c.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                BP_Game__c.Id,
                BP_Game__c.Name,
                BP_Game__c.BP_Type__c,
                BP_Game__c.BP_Category__c,
                BP_Game__c.BP_Mechanic__c,
                BP_Game__c.BP_RecommendedAge__c
        };
    }

    public List<BP_Game__c> selectById(Set<Id> ids) {
        return (List<BP_Game__c>)selectSObjectsById(ids);
    }

    public List<BP_Game__c> selectByIdAndHasExpansion(Set<Id> ids, Boolean hasExpansion) {
        final fflib_QueryFactory queryFactory = newQueryFactory()
                .selectField(BP_Game__c.BP_HasExpansion__c)
                .selectField(BP_Game__c.BP_IsExpansion__c)
                .setCondition('Id IN :ids AND BP_HasExpansion__c = :hasExpansion');
        return Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
    }

    public interface BP_IGameSelector {
        SObjectType getSObjectType();
        List<SObjectField> getSObjectFieldList();
        List<BP_Game__c> selectById(Set<Id> ids);
        List<BP_Game__c> selectByIdAndHasExpansion(Set<Id> ids, Boolean hasExpansion);
    }
}