src/main/default/objects/BP_Game__c/BP_Game__c.object-meta.xml
<CustomObject>
    <description>Game object</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_Gameplay__c/BP_Gameplay__c.object-meta.xml
<CustomObject>
    <label>Gameplay</label>
    <nameField>
        <label>Game Play Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gameplays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/BP_Gameplay__c/fields/BP_Game__c.field-meta.xml
<CustomField>
    <fullName>BP_Game__c</fullName>
    <label>Game</label>
    <referenceTo>BP_CollectionItem__c</referenceTo>
    <relationshipName>Game_Plays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/main/default/objects/BP_Gameplay__c/fields/BP_PlayDate__c.field-meta.xml
<CustomField>
    <fullName>BP_PlayDate__c</fullName>
    <label>Play Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/BP_Gameplay__c/fields/BP_Winner__c.field-meta.xml
<CustomField>
    <fullName>BP_Winner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gameplays</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/selector/BP_GameplaySelector.cls
/**
 * Created by Jedrzej Gruca on 02/12/2023.
 */

public with sharing class BP_GameplaySelector extends fflib_SObjectSelector implements BP_IGameplaySelector {

    public BP_GameplaySelector() {
        super();
    }

    public static BP_GameplaySelector newInstance() {
        return (BP_GameplaySelector) BP_Application.selector.newInstance(BP_Gameplay__c.SObjectType);
    }

    public SObjectType getSObjectType() {
        return BP_Gameplay__c.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                BP_Gameplay__c.Id,
                BP_Gameplay__c.Name,
                BP_Gameplay__c.BP_Game__c,
                BP_Gameplay__c.BP_PlayDate__c,
                BP_Gameplay__c.BP_Winner__c
        };
    }

    public List<BP_Gameplay__c> selectById(Set<Id> ids) {
        return (List<BP_Gameplay__c>)selectSObjectsById(ids);
    }

    public interface BP_IGameplaySelector {
        SObjectType getSObjectType();
        List<SObjectField> getSObjectFieldList();
        List<BP_Gameplay__c> selectById(Set<Id> ids);
    }
}