src/main/default/objects/BP_CollectionItem__c/BP_CollectionItem__c.object-meta.xml
<CustomObject>
    <label>Collection Item</label>
    <nameField>
        <label>Collection Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_CollectionItem__c/fields/BP_GameCondition__c.field-meta.xml
<CustomField>
    <fullName>BP_GameCondition__c</fullName>
    <label>Game Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/classes/selector/test/BP_CollectionItemSelectorTest.cls
/**
 * Created by Jedrzej Gruca on 08/02/2024.
 */

@IsTest
public with sharing class BP_CollectionItemSelectorTest {

    @IsTest
    private static void selectById() {
        final BP_CollectionItem__c item = new BP_CollectionItem__c(
                Name = 'Gra',
                BP_GameCondition__c = 'New'
        );
        insert item;

        Test.startTest();
        final List<BP_CollectionItem__c> items = BP_CollectionItemSelector.newInstance().selectById(new Set<Id>{item.Id});
        Test.stopTest();

        Assert.areEqual(1, items.size());
    }
}