src/main/default/objects/BP_CollectionItem__c/BP_CollectionItem__c.object-meta.xml
<CustomObject>
    <label>Collection Item</label>
    <nameField>
        <label>Collection Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_CollectionItem__c/fields/BP_ConditionDetails__c.field-meta.xml
<CustomField>
    <fullName>BP_ConditionDetails__c</fullName>
    <label>Condition Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/BP_CollectionItem__c/fields/BP_Game__c.field-meta.xml
<CustomField>
    <fullName>BP_Game__c</fullName>
    <label>Game</label>
    <referenceTo>BP_Game__c</referenceTo>
    <relationshipLabel>Collection Items</relationshipLabel>
    <relationshipName>Collection_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/BP_CollectionItem__c/fields/BP_GameCondition__c.field-meta.xml
<CustomField>
    <fullName>BP_GameCondition__c</fullName>
    <label>Game Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BP_CollectionItem__c/fields/BP_Owner__c.field-meta.xml
<CustomField>
    <fullName>BP_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Collection Items</relationshipLabel>
    <relationshipName>Collection_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/BP_CollectionItem__c/fields/BP_PurchaseDate__c.field-meta.xml
<CustomField>
    <fullName>BP_PurchaseDate__c</fullName>
    <label>Purchase Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/BP_Game__c/BP_Game__c.object-meta.xml
<CustomObject>
    <description>Game object</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/selector/BP_CollectionItemSelector.cls
/**
 * Created by Jedrzej Gruca on 19/11/2023.
 */

public with sharing class BP_CollectionItemSelector extends fflib_SObjectSelector implements BP_ICollectionItemSelector {

    public BP_CollectionItemSelector() {
        super();
    }

    public static BP_CollectionItemSelector newInstance() {
        return (BP_CollectionItemSelector) BP_Application.selector.newInstance(BP_CollectionItem__c.SObjectType);
    }

    public SObjectType getSObjectType() {
        return BP_CollectionItem__c.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                BP_CollectionItem__c.Id,
                BP_CollectionItem__c.Name,
                BP_CollectionItem__c.BP_Game__c,
                BP_CollectionItem__c.BP_GameCondition__c,
                BP_CollectionItem__c.BP_ConditionDetails__c,
                BP_CollectionItem__c.BP_Owner__c,
                BP_CollectionItem__c.BP_PurchaseDate__c
        };
    }

    public List<BP_CollectionItem__c> selectById(Set<Id> ids) {
        return (List<BP_CollectionItem__c>)selectSObjectsById(ids);
    }

    public interface BP_ICollectionItemSelector {
        SObjectType getSObjectType();
        List<SObjectField> getSObjectFieldList();
        List<BP_CollectionItem__c> selectById(Set<Id> ids);
    }
}