src/main/default/objects/BP_CollectionItem__c/BP_CollectionItem__c.object-meta.xml
<CustomObject>
    <label>Collection Item</label>
    <nameField>
        <label>Collection Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_CollectionItem__c/fields/BP_Game__c.field-meta.xml
<CustomField>
    <fullName>BP_Game__c</fullName>
    <label>Game</label>
    <referenceTo>BP_Game__c</referenceTo>
    <relationshipLabel>Collection Items</relationshipLabel>
    <relationshipName>Collection_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/BP_CollectionItem__c/fields/BP_GameCondition__c.field-meta.xml
<CustomField>
    <fullName>BP_GameCondition__c</fullName>
    <label>Game Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BP_Game__c/BP_Game__c.object-meta.xml
<CustomObject>
    <description>Game object</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_Gameplay__c/BP_Gameplay__c.object-meta.xml
<CustomObject>
    <label>Gameplay</label>
    <nameField>
        <label>Game Play Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gameplays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/BP_Gameplay__c/fields/BP_Game__c.field-meta.xml
<CustomField>
    <fullName>BP_Game__c</fullName>
    <label>Game</label>
    <referenceTo>BP_CollectionItem__c</referenceTo>
    <relationshipName>Game_Plays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/main/default/classes/selector/test/BP_GameplaySelectorTest.cls
/**
 * Created by Jedrzej Gruca on 08/02/2024.
 */

@IsTest
public with sharing class BP_GameplaySelectorTest {

    @IsTest
    private static void selectByIdTest() {
        final BP_CollectionItem__c item = new BP_CollectionItem__c(
                Name = 'Gra',
                BP_GameCondition__c = 'New'
        );
        insert item;

        final BP_Gameplay__c gameplay = new BP_Gameplay__c(
                Name = 'Rozgrywka',
                BP_Game__c = item.Id
        );
        insert gameplay;

        Test.startTest();
        final List<BP_Gameplay__c> gameplays = BP_GameplaySelector.newInstance().selectById(new Set<Id>{gameplay.Id});
        Test.stopTest();

        Assert.areEqual(1, gameplays.size());
    }
}