src/main/default/objects/BP_CollectionItem__c/BP_CollectionItem__c.object-meta.xml
<CustomObject>
    <label>Collection Item</label>
    <nameField>
        <label>Collection Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_CollectionItem__c/fields/BP_Game__c.field-meta.xml
<CustomField>
    <fullName>BP_Game__c</fullName>
    <label>Game</label>
    <referenceTo>BP_Game__c</referenceTo>
    <relationshipLabel>Collection Items</relationshipLabel>
    <relationshipName>Collection_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/BP_CollectionItem__c/fields/BP_GameCondition__c.field-meta.xml
<CustomField>
    <fullName>BP_GameCondition__c</fullName>
    <label>Game Condition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BP_Game__c/BP_Game__c.object-meta.xml
<CustomObject>
    <description>Game object</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_Gameplay__c/BP_Gameplay__c.object-meta.xml
<CustomObject>
    <label>Gameplay</label>
    <nameField>
        <label>Game Play Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gameplays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/BP_Gameplay__c/fields/BP_Game__c.field-meta.xml
<CustomField>
    <fullName>BP_Game__c</fullName>
    <label>Game</label>
    <referenceTo>BP_CollectionItem__c</referenceTo>
    <relationshipName>Game_Plays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/main/default/objects/BP_Score__c/BP_Score__c.object-meta.xml
<CustomObject>
    <label>Score</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/BP_Score__c/fields/BP_GamePlay__c.field-meta.xml
<CustomField>
    <fullName>BP_GamePlay__c</fullName>
    <label>Game Play</label>
    <referenceTo>BP_Gameplay__c</referenceTo>
    <relationshipLabel>Scores</relationshipLabel>
    <relationshipName>Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/BP_Score__c/fields/BP_Value__c.field-meta.xml
<CustomField>
    <fullName>BP_Value__c</fullName>
    <label>Value</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/selector/test/BP_ScoreSelectorTest.cls
/**
 * Created by Jedrzej Gruca on 08/02/2024.
 */

@IsTest
public with sharing class BP_ScoreSelectorTest {

    @TestSetup
    static void testSetup() {
        final BP_CollectionItem__c item = new BP_CollectionItem__c(
                Name = 'Game',
                BP_GameCondition__c = 'New'
        );
        insert item;

        final BP_Gameplay__c gameplay = new BP_Gameplay__c(
                Name = 'Gameplay',
                BP_Game__c = item.Id
        );
        insert gameplay;

        final BP_Score__c score = new BP_Score__c(
                BP_GamePlay__c = gameplay.Id,
                BP_Value__c = 10
        );
        insert score;
    }

    @IsTest
    private static void selectByIdTest() {
        Id scoreId = [SELECT Id FROM BP_Score__c].get(0).Id;

        Test.startTest();
        final List<BP_Score__c> scores = BP_ScoreSelector.newInstance().selectById(new Set<Id>{scoreId});
        Test.stopTest();

        Assert.areEqual(1, scores.size());
    }

    @IsTest
    private static void selectByGameplayIdTest() {
        Id gameplayId = [SELECT Id FROM BP_Gameplay__c].get(0).Id;

        Test.startTest();
        final List<BP_Score__c> scores = BP_ScoreSelector.newInstance().selectByGameplayId(new Set<Id>{gameplayId});
        Test.stopTest();

        Assert.areEqual(1, scores.size());
    }
}