src/main/default/objects/BP_Gameplay__c/BP_Gameplay__c.object-meta.xml
<CustomObject>
    <label>Gameplay</label>
    <nameField>
        <label>Game Play Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gameplays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/BP_Player__c/BP_Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_Score__c/BP_Score__c.object-meta.xml
<CustomObject>
    <label>Score</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/BP_Score__c/fields/BP_GamePlay__c.field-meta.xml
<CustomField>
    <fullName>BP_GamePlay__c</fullName>
    <label>Game Play</label>
    <referenceTo>BP_Gameplay__c</referenceTo>
    <relationshipLabel>Scores</relationshipLabel>
    <relationshipName>Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/BP_Score__c/fields/BP_Player__c.field-meta.xml
<CustomField>
    <fullName>BP_Player__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Scores</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/BP_Score__c/fields/BP_Value__c.field-meta.xml
<CustomField>
    <fullName>BP_Value__c</fullName>
    <label>Value</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/selector/BP_ScoreSelector.cls
/**
 * Created by Jedrzej Gruca on 02/12/2023.
 */

public with sharing class BP_ScoreSelector extends fflib_SObjectSelector implements BP_IScoreSelector {

    public BP_ScoreSelector() {
        super();
    }

    public static BP_ScoreSelector newInstance() {
        return (BP_ScoreSelector) BP_Application.selector.newInstance(BP_Score__c.SObjectType);
    }

    public SObjectType getSObjectType() {
        return BP_Score__c.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                BP_Score__c.Id,
                BP_Score__c.Name,
                BP_Score__c.BP_GamePlay__c,
                BP_Score__c.BP_Player__c,
                BP_Score__c.BP_Value__c
        };
    }

    public List<BP_Score__c> selectById(Set<Id> ids) {
        return (List<BP_Score__c>)selectSObjectsById(ids);
    }

    public List<BP_Score__c> selectByGameplayId(Set<Id> ids) {
        final fflib_QueryFactory queryFactory = newQueryFactory()
                .setCondition('BP_GamePlay__c IN :ids')
                .setOrdering(BP_Score__c.BP_Value__c, fflib_QueryFactory.SortOrder.DESCENDING);
        return Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
    }

    public interface BP_IScoreSelector {
        SObjectType getSObjectType();
        List<SObjectField> getSObjectFieldList();
        List<BP_Score__c> selectById(Set<Id> ids);
        List<BP_Score__c> selectByGameplayId(Set<Id> ids);
    }
}