src/main/default/objects/BP_Gameplay__c/BP_Gameplay__c.object-meta.xml
<CustomObject>
    <label>Gameplay</label>
    <nameField>
        <label>Game Play Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gameplays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/BP_Gameplay__c/fields/BP_Winner__c.field-meta.xml
<CustomField>
    <fullName>BP_Winner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gameplays</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/BP_Player__c/BP_Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_Score__c/BP_Score__c.object-meta.xml
<CustomObject>
    <label>Score</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/BP_Score__c/fields/BP_GamePlay__c.field-meta.xml
<CustomField>
    <fullName>BP_GamePlay__c</fullName>
    <label>Game Play</label>
    <referenceTo>BP_Gameplay__c</referenceTo>
    <relationshipLabel>Scores</relationshipLabel>
    <relationshipName>Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/BP_Score__c/fields/BP_Player__c.field-meta.xml
<CustomField>
    <fullName>BP_Player__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Scores</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/domain/BP_Scores.cls
/**
 * Created by Jedrzej Gruca on 02/12/2023.
 */

public with sharing class BP_Scores extends fflib_SObjectDomain {

    public BP_Scores(List<BP_Score__c> sObjectList) {
        super(sObjectList);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new BP_Scores(sObjectList);
        }
    }

    public override void onAfterInsert() {
        setNewWinnerOnRelatedGameplay();
    }

    private void setNewWinnerOnRelatedGameplay() {
        final Set<Id> gameplayIds = new Set<Id>();
        for (BP_Score__c score : (List<BP_Score__c>)Records) {
            gameplayIds.add(score.BP_GamePlay__c);
        }
        if (gameplayIds.isEmpty()) {
            return;
        }
        final List<BP_Score__c> scores = BP_ScoreSelector.newInstance().selectByGameplayId(gameplayIds);
        final Map<Id, BP_Score__c> gameplayToHighestScoreMap = new Map<Id, BP_Score__c>();
        for (BP_Score__c sc : scores) {
            if (gameplayToHighestScoreMap.containsKey(sc.BP_GamePlay__c)) {
                continue;
            } else {
                gameplayToHighestScoreMap.put(sc.BP_GamePlay__c, sc);
            }
        }
        final List<BP_Gameplay__c> gameplaysToUpdate = BP_GameplaySelector.newInstance().selectById(gameplayToHighestScoreMap.keySet());
        final fflib_ISObjectUnitOfWork uow = BP_Application.unitOfWork.newInstance(new List<SObjectType>{BP_Gameplay__c.SObjectType});
        for (BP_Gameplay__c gp : gameplaysToUpdate) {
            if (gp.BP_Winner__c == gameplayToHighestScoreMap.get(gp.Id).BP_Player__c) {
                continue;
            } else {
                gp.BP_Winner__c = gameplayToHighestScoreMap.get(gp.Id).BP_Player__c;
                uow.registerDirty(gp);
            }
        }
        uow.commitWork();
    }
}