src/main/default/objects/Account/fields/BP_NumberOfExpansions__c.field-meta.xml
<CustomField>
    <fullName>BP_NumberOfExpansions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Expansions</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Account/fields/BP_NumberOfGames__c.field-meta.xml
<CustomField>
    <fullName>BP_NumberOfGames__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Games</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/BP_Game__c/BP_Game__c.object-meta.xml
<CustomObject>
    <description>Game object</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BP_Game__c/fields/BP_bggId__c.field-meta.xml
<CustomField>
    <fullName>BP_bggId__c</fullName>
    <externalId>true</externalId>
    <label>BGG Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_Description__c.field-meta.xml
<CustomField>
    <fullName>BP_Description__c</fullName>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_ExpansionFor__c.field-meta.xml
<CustomField>
    <fullName>BP_ExpansionFor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to main game</description>
    <label>Expansion For</label>
    <referenceTo>BP_Game__c</referenceTo>
    <relationshipLabel>Expansions</relationshipLabel>
    <relationshipName>Expansions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_IsExpansion__c.field-meta.xml
<CustomField>
    <fullName>BP_IsExpansion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if game is expansion to another game</description>
    <label>Is Expansion</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_MaximumPlayersNumber__c.field-meta.xml
<CustomField>
    <fullName>BP_MaximumPlayersNumber__c</fullName>
    <label>Maximum Players Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_MinimumPlayersNumber__c.field-meta.xml
<CustomField>
    <fullName>BP_MinimumPlayersNumber__c</fullName>
    <label>Minimum Players Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/BP_Game__c/fields/BP_Publisher__c.field-meta.xml
<CustomField>
    <fullName>BP_Publisher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Publisher</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Games</relationshipLabel>
    <relationshipName>Games</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/domain/test/BP_GamesWithoutFflibMocksTest.cls
/**
 * Created by Jedrzej Gruca on 09/02/2024.
 */

@IsTest
public with sharing class BP_GamesWithoutFflibMocksTest {

    @IsTest
    private static void setProperDescriptionTest() {
        final BP_Game__c fakeGame = new BP_Game__c(
                BP_Description__c = 'board  game',
                BP_bggId__c = 1,
                BP_MinimumPlayersNumber__c = 1,
                BP_MaximumPlayersNumber__c = 4
        );
        insert fakeGame;

        final BP_Game__c gameAfterInsert = [SELECT Id, BP_Description__c FROM BP_Game__c WHERE Id = :fakeGame.Id].get(0);

        Assert.areEqual('board game', gameAfterInsert.BP_Description__c);
    }

    @IsTest
    private static void setHasExpansionOnParentGameTest() {
        final BP_Game__c fakeGame = new BP_Game__c(
                BP_Description__c = 'Game',
                BP_bggId__c = 1,
                BP_MinimumPlayersNumber__c = 1,
                BP_MaximumPlayersNumber__c = 4
        );
        insert fakeGame;

        final BP_Game__c fakeExpansion = new BP_Game__c(
                BP_Description__c = 'Expansion',
                BP_bggId__c = 2,
                BP_MinimumPlayersNumber__c = 1,
                BP_MaximumPlayersNumber__c = 4
        );
        insert fakeExpansion;

        Test.startTest();
        fakeExpansion.BP_IsExpansion__c = true;
        fakeExpansion.BP_ExpansionFor__c = fakeGame.Id;
        update fakeExpansion;
        Test.stopTest();

        final BP_Game__c game = [SELECT BP_ExpansionFor__c FROM BP_Game__c WHERE Id = :fakeExpansion.Id].get(0);
        Assert.areEqual(fakeGame.Id, game.BP_ExpansionFor__c);
    }

    @IsTest
    private static void setNumberOfGamesOnPublisher() {
        final Account fakePublisher = new Account(
                Name = 'Publisher',
                BP_NumberOfGames__c = 0,
                BP_NumberOfExpansions__c = 0
        );
        insert fakePublisher;

        final BP_Game__c fakeGame = new BP_Game__c(
                BP_Description__c = 'Game',
                BP_bggId__c = 1,
                BP_MinimumPlayersNumber__c = 1,
                BP_MaximumPlayersNumber__c = 4
        );
        insert fakeGame;

        final BP_Game__c fakeExpansion = new BP_Game__c(
                BP_Description__c = 'Expansion',
                BP_bggId__c = 2,
                BP_MinimumPlayersNumber__c = 1,
                BP_MaximumPlayersNumber__c = 4
        );
        insert fakeExpansion;

        Test.startTest();
        List<BP_Game__c> toUpdate = new List<BP_Game__c>();
        fakeGame.BP_Publisher__c = fakePublisher.Id;
        toUpdate.add(fakeGame);
        fakeExpansion.BP_Publisher__c = fakePublisher.Id;
        fakeExpansion.BP_IsExpansion__c = true;
        fakeExpansion.BP_ExpansionFor__c = fakeGame.Id;
        toUpdate.add(fakeExpansion);
        update toUpdate;
        Test.stopTest();

        final Account publisher = [SELECT BP_NumberOfGames__c, BP_NumberOfExpansions__c FROM Account WHERE Id = :fakePublisher.Id].get(0);
        Assert.areEqual(1, publisher.BP_NumberOfGames__c);
        Assert.areEqual(1, publisher.BP_NumberOfExpansions__c);
    }
}