src/main/default/objects/Account/fields/BP_NumberOfExpansions__c.field-meta.xml
<CustomField>
    <fullName>BP_NumberOfExpansions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Expansions</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Account/fields/BP_NumberOfGames__c.field-meta.xml
<CustomField>
    <fullName>BP_NumberOfGames__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Games</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/selector/BP_AccountSelector.cls
/**
 * Created by Jedrzej Gruca on 11/11/2023.
 */

public with sharing class BP_AccountSelector extends fflib_SObjectSelector implements BP_IAccountSelector {

    public BP_AccountSelector() {
        super();
    }

    public static BP_AccountSelector newInstance() {
        return (BP_AccountSelector) BP_Application.selector.newInstance(Account.SObjectType);
    }

    public SObjectType getSObjectType() {
        return Account.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Account.Id,
                Account.Name,
                Account.BP_NumberOfGames__c,
                Account.BP_NumberOfExpansions__c
        };
    }

    public List<Account> selectById(Set<Id> ids) {
        return (List<Account>)selectSObjectsById(ids);
    }

    public List<Account> selectByIdWithAdditionalFields(Set<Id> ids) {
        final fflib_QueryFactory queryFactory = newQueryFactory()
                .selectField(Account.Location__Latitude__s)
                .selectField(Account.Location__Longitude__s)
                .setCondition('Id IN :ids');
        return Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
    }

    public interface BP_IAccountSelector {
        SObjectType getSObjectType();
        List<SObjectField> getSObjectFieldList();
        List<Account> selectById(Set<Id> ids);
    }
}